#!/bin/bash

# This checks /proc/cmdline for the LAST 'flash=' statement, and considers
# it as a partition number and mounts the next one into /nv, which
# is created if it does not exist

export PATH=/bin:/sbin:/usr/bin:/usr/sbin
PERSIST_DIR=/nv

# return the detected flash in $FLASH_SW
find_flash() {
  local flash

  unset FLASH_MBR FLASH_HW FLASH_SW FLASH_NV

  if [ -s /var/state/flash-layout.rc ]; then
    . /var/state/flash-layout.rc
  fi

  if [ -z "$FLASH_SW" ]; then
    if [ -x /sbin/mk-flash-layout ]; then
      /sbin/mk-flash-layout ${MOUNTED_RO:+-k} ${QUIET:+-q}
      if [ -s /var/state/flash-layout.rc ]; then
        . /var/state/flash-layout.rc
      fi
    fi
  fi

  if [ -z "$FLASH_SW" ]; then
    flash="$(cat /proc/cmdline)"
    if [ -n "${flash##*flash=*}" ]; then
      [ -z "$QUIET" ] && echo "No flash device specified in /proc/cmdline."
      return 1
    fi
    flash=${flash##*flash=}
    flash=${flash%% *}
    [ -n "${flash##/dev/*}" ] && flash="/dev/$flash"
    FLASH_SW=$flash
  fi
  return 0
}

if ! find_flash; then
  echo "Flash not found."
  exit 1
fi

# Most often, mk-flash-layout will not detect the non-volatile partition.
# The solution consists in derivating it from $FLASH_SW.
if [ -z "$FLASH_NV" ]; then
  partnum=${FLASH_SW##*[^0-9]}
  radix=${FLASH_SW%$partnum}

  newpart=$(( partnum + 1 ))
  FLASH_NV=${radix}${newpart}
fi

# We first unmount $PERSIST_DIR if anything was mounted on it.
# Then, we'll copy anything we find in it into the new FS.

cd /
umount -d $PERSIST_DIR >/dev/null 2>&1
modprobe -r block2mtd   >/dev/null 2>&1

modprobe mtdblock >/dev/null 2>&1
modprobe block2mtd block2mtd=$FLASH_NV,65536 >/dev/null 2>&1

mtd=$(grep -wF $FLASH_NV /proc/mtd)
mtd=${mtd%%:*}
mtd=${mtd##*[^0-9]}
mtdblock=/dev/mtdblock${mtd}

# trick: we enter the directory before we remount over it
if mkdir -p $PERSIST_DIR 2>/dev/null; then
  echo "Mounting $mtdblock($FLASH_NV) on $PERSIST_DIR..."
  cd $PERSIST_DIR
  retmsg=$(mount -t jffs2 $mtdblock $PERSIST_DIR 2>&1)
  ret="$?"
  if [ "$ret" != "0" ] ; then
    retmsg=$( echo "$retmsg" | grep "bad superblock")
    if [ -n "$retmsg" ] ; then
	if [ "$1" = "--format" ] ; then
		tr '\000' '\377' </dev/zero | dd of=$mtdblock bs=64k 2>/dev/null
		mount -t jffs2 $mtdblock $PERSIST_DIR 2>/dev/null
		if [ "$?" != "0" ] ; then
			echo "Unable to format."
		fi
	else
		echo "Error: mount failed, nv seems not formatted use option --format."
		modprobe -r block2mtd mtdblock 2>/dev/null
		exit 1
	fi
    else
	echo "Error: mount failed."
	modprobe -r block2mtd mtdblock 2>/dev/null
	exit 1
    fi
  fi

   # now we will copy everything currently in this directory over the
   # new file-system.
   cp -a . $PERSIST_DIR/
   cd $PERSIST_DIR

else
  echo "Error: cannot make directory $PERSIST_DIR."
  modprobe -r block2mtd mtdblock 2>/dev/null
  exit 1
fi

exit 0
